Watching for file changes with StatReloader
"GET /homework/ HTTP/1.1" 200 779
"GET /homework/about HTTP/1.1" 200 1293
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/ HTTP/1.1" 200 779
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/ HTTP/1.1" 200 779
Not Found: /favicon.ico
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/ HTTP/1.1" 200 779
Not Found: /favicon.ico
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/ HTTP/1.1" 200 779
"GET /homework/about HTTP/1.1" 200 1293
"GET /homework/about HTTP/1.1" 200 1293
"GET /homework/ HTTP/1.1" 200 779
"GET /homework/ HTTP/1.1" 200 779
"GET /homework/about HTTP/1.1" 200 1293
Watching for file changes with StatReloader
Not Found: /
"GET / HTTP/1.1" 404 2276
Not Found: /game/head_or_tail/
"GET /game/head_or_tail/ HTTP/1.1" 404 2936
Not Found: /favicon.ico
"GET /game/head_or_tail HTTP/1.1" 200 10
Not Found: /favicon.ico
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /game/head_or_tail HTTP/1.1" 301 0
"GET /game/head_or_tail/ HTTP/1.1" 200 10
Not Found: /favicon.ico
"GET /game/head_or_tail/ HTTP/1.1" 200 10
Not Found: /favicon.ico
/home/denis/Documents/GeekBrains/025_Django/django_seminars/myproject/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/myproject/settings.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/models.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/models.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/models.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/models.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/models.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /homework/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 18, in index
    return render(request, "homeworkapp/templates/simple_template.html", context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: homeworkapp/templates/simple_template.html
"GET /homework/ HTTP/1.1" 500 83610
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 18, in index
    return render(request, "/homeworkapp/templates/simple_template.html", context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: /homeworkapp/templates/simple_template.html
"GET /homework/ HTTP/1.1" 500 82423
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/ HTTP/1.1" 200 790
Internal Server Error: /homework/about
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 27, in about
    return render(request, "homeworkapp/templates/simple_template.html", context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: homeworkapp/templates/simple_template.html
"GET /homework/about HTTP/1.1" 500 82604
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/about HTTP/1.1" 200 731
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/about HTTP/1.1" 200 731
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Internal Server Error: /game/head_or_tail/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_response(request, response)
  File "/usr/lib/python3/dist-packages/django/middleware/clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'int' object has no attribute 'get'
"GET /game/head_or_tail/ HTTP/1.1" 500 67102
"GET /game/head_or_tail/6 HTTP/1.1" 301 0
"GET /game/head_or_tail/6/ HTTP/1.1" 200 8
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /game/head_or_tail/6/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_response(request, response)
  File "/usr/lib/python3/dist-packages/django/middleware/clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'int' object has no attribute 'get'
"GET /game/head_or_tail/6/ HTTP/1.1" 500 67122
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /game/head_or_tail/6/ HTTP/1.1" 200 1
"GET /game/head_or_tail/ HTTP/1.1" 200 8
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /game/head_or_tail/ HTTP/1.1" 200 68
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /game/head_or_tail/2 HTTP/1.1" 301 0
Internal Server Error: /game/head_or_tail/2/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py", line 12, in head_or_tail
    return HttpResponse(str(*results))
TypeError: decoding str is not supported
"GET /game/head_or_tail/2/ HTTP/1.1" 500 67821
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /game/head_or_tail/2/ HTTP/1.1" 200 68
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /game/head_or_tail/2/ HTTP/1.1" 200 68
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /game/head_or_tail/2/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py", line 14, in head_or_tail
    print(**results)
TypeError: print() argument after ** must be a mapping, not generator
"GET /game/head_or_tail/2/ HTTP/1.1" 500 67934
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /game/head_or_tail/2/ HTTP/1.1" 200 26
Not Found: /favicon.ico
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /game/head_or_tail/2/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py", line 18, in head_or_tail
    return render(response, "gameapp/game_results.html", context)
NameError: name 'response' is not defined
"GET /game/head_or_tail/2/ HTTP/1.1" 500 68028
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /game/head_or_tail/2/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py", line 18, in head_or_tail
    return render(request, "gameapp/game_results.html", context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 806, in do_for
    raise TemplateSyntaxError("'for' statements should use the format"
django.template.exceptions.TemplateSyntaxError: 'for' statements should use the format 'for x in y': for attempt, result in enumerate(1, results)
"GET /game/head_or_tail/2/ HTTP/1.1" 500 130080
Internal Server Error: /game/head_or_tail/2/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py", line 18, in head_or_tail
    return render(request, "gameapp/game_results.html", context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 816, in do_for
    sequence = parser.compile_filter(bits[in_index + 1])
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ')' from 'results)'
"GET /game/head_or_tail/2/ HTTP/1.1" 500 139531
Not Found: /favicon.ico
"GET /game/head_or_tail/2/ HTTP/1.1" 200 834
"GET /game/head_or_tail/2/ HTTP/1.1" 200 838
"GET /game/head_or_tail/2/ HTTP/1.1" 200 840
"GET /game/head_or_tail/20/ HTTP/1.1" 200 2042
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/gameapp/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /game/dice/20/ HTTP/1.1" 200 1874
"GET /game/random/20/ HTTP/1.1" 200 1902
/home/denis/Documents/GeekBrains/025_Django/django_seminars/myproject/settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 127, in render
    compiled_parent = self.get_parent(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 124, in get_parent
    return self.find_template(parent, context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 103, in find_template
    template, origin = context.template.engine.find_template(
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 129, in find_template
    raise TemplateDoesNotExist(name, tried=tried)
django.template.exceptions.TemplateDoesNotExist: base.html

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 19, in index
    return render(request, "homeworkapp/simple_template.html", context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 63, in render
    reraise(exc, self.backend)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 84, in reraise
    raise new from exc
django.template.exceptions.TemplateDoesNotExist: base.html
"GET /homework/ HTTP/1.1" 500 129844
"GET /homework/ HTTP/1.1" 200 807
/home/denis/Documents/GeekBrains/025_Django/django_seminars/myproject/urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /author
"GET /author HTTP/1.1" 404 2420
Not Found: /blogapp/author
"GET /blogapp/author HTTP/1.1" 404 2533
Internal Server Error: /blogapp/author/6
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
TypeError: AuthorPosts.get() got an unexpected keyword argument 'id'
"GET /blogapp/author/6 HTTP/1.1" 500 73393
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /blogapp/author/6 HTTP/1.1" 200 1
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /blogapp/author/6
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py", line 9, in get
    author = get_object_or_404(Author, pk=author_id)
NameError: name 'get_object_or_404' is not defined
"GET /blogapp/author/6 HTTP/1.1" 500 77379
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /blogapp/author/6 HTTP/1.1" 200 1023
"GET /blogapp/author/6 HTTP/1.1" 200 1073
"GET /blogapp/author/6 HTTP/1.1" 200 1073
"GET /blogapp/author/6 HTTP/1.1" 200 1843
Watching for file changes with StatReloader
"GET /blogapp/author/6 HTTP/1.1" 200 2971
"GET /blogapp/author/6 HTTP/1.1" 200 2971
"GET /blogapp/author/6 HTTP/1.1" 200 2971
"GET /blogapp/author/6 HTTP/1.1" 200 3125
Not Found: /blogapp/author/666
"GET /blogapp/author/666 HTTP/1.1" 404 2715
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /blogapp/author/16
"GET /blogapp/author/16 HTTP/1.1" 404 2712
Internal Server Error: /blogapp/author/3
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py", line 14, in get
    "posts": Post.objects.filter(author=author)
NameError: name 'author' is not defined
"GET /blogapp/author/3 HTTP/1.1" 500 76936
Internal Server Error: /blogapp/author/7
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py", line 14, in get
    "posts": Post.objects.filter(author=author)
NameError: name 'author' is not defined
"GET /blogapp/author/7 HTTP/1.1" 500 76936
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /blogapp/author/7 HTTP/1.1" 200 3113
"GET /blogapp/author/8 HTTP/1.1" 200 3117
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /blogapp/author/8
"GET /blogapp/author/8 HTTP/1.1" 404 2709
Not Found: /blogapp/author/80
"GET /blogapp/author/80 HTTP/1.1" 404 2712
Not Found: /blogapp/author/24
"GET /blogapp/author/24 HTTP/1.1" 404 2712
Internal Server Error: /blogapp/author/26
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py", line 16, in get
    return render(request, "blogapp/author_posts.html", context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 817, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 968, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '{{ forloop.counter' from '{{ forloop.counter'
"GET /blogapp/author/26 HTTP/1.1" 500 203312
"GET /blogapp/author/26 HTTP/1.1" 200 869
"GET /blogapp/author/29 HTTP/1.1" 200 1641
"GET /blogapp/author/34 HTTP/1.1" 200 1585
Internal Server Error: /blogapp/post/348
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/db/models/fields/__init__.py", line 1823, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Author'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py", line 21, in get
    author = get_object_or_404(Author, pk=post.author)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 76, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 1423, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 1442, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 1377, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 1223, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/usr/lib/python3/dist-packages/django/db/models/lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "/usr/lib/python3/dist-packages/django/db/models/lookups.py", line 301, in get_prep_lookup
    return super().get_prep_lookup()
  File "/usr/lib/python3/dist-packages/django/db/models/lookups.py", line 77, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/usr/lib/python3/dist-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <Author: Author 9>.
"GET /blogapp/post/348 HTTP/1.1" 500 145735
Internal Server Error: /blogapp/post/362
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/db/models/fields/__init__.py", line 1823, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'Author'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py", line 21, in get
    author = get_object_or_404(Author, pk=post.author)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 76, in get_object_or_404
    return queryset.get(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 424, in get
    clone = self._chain() if self.query.combinator else self.filter(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "/usr/lib/python3/dist-packages/django/db/models/query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 1423, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 1442, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 1377, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/usr/lib/python3/dist-packages/django/db/models/sql/query.py", line 1223, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/usr/lib/python3/dist-packages/django/db/models/lookups.py", line 25, in __init__
    self.rhs = self.get_prep_lookup()
  File "/usr/lib/python3/dist-packages/django/db/models/lookups.py", line 301, in get_prep_lookup
    return super().get_prep_lookup()
  File "/usr/lib/python3/dist-packages/django/db/models/lookups.py", line 77, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/usr/lib/python3/dist-packages/django/db/models/fields/__init__.py", line 1825, in get_prep_value
    raise e.__class__(
TypeError: Field 'id' expected a number but got <Author: Author 9>.
"GET /blogapp/post/362 HTTP/1.1" 500 145736
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /blogapp/post/362 HTTP/1.1" 200 932
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /blogapp/author/1 HTTP/1.1" 200 869
Not Found: /blogapp/author/26
"GET /blogapp/author/26 HTTP/1.1" 404 2712
"GET /blogapp/author/2 HTTP/1.1" 200 2725
"GET /blogapp/post/15 HTTP/1.1" 200 932
"GET /blogapp/post/29 HTTP/1.1" 200 932
"GET /blogapp/post/71 HTTP/1.1" 200 932
"GET /blogapp/post/141 HTTP/1.1" 200 932
"GET /blogapp/post/15 HTTP/1.1" 200 932
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /blogapp/post/43 HTTP/1.1" 200 1171
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /blogapp/post/71 HTTP/1.1" 200 1165
"GET /blogapp/post/141 HTTP/1.1" 200 1170
"GET /blogapp/post/141 HTTP/1.1" 200 1172
"GET /blogapp/post/57 HTTP/1.1" 200 1170
"GET /blogapp/post/85 HTTP/1.1" 200 1121
"GET /blogapp/post/85 HTTP/1.1" 200 1127
"GET /blogapp/post/85 HTTP/1.1" 200 1124
"GET /blogapp/post/85 HTTP/1.1" 200 1132
"GET /blogapp/post/85 HTTP/1.1" 200 1132
"GET /blogapp/post/85 HTTP/1.1" 200 1132
"GET /blogapp/post/85 HTTP/1.1" 200 1132
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /blogapp/post/85
"GET /blogapp/post/85 HTTP/1.1" 404 2899
"GET /blogapp/author/1 HTTP/1.1" 200 869
"GET /blogapp/author/1 HTTP/1.1" 200 869
Not Found: /blogapp/author/11
"GET /blogapp/author/11 HTTP/1.1" 404 2712
"GET /blogapp/author/1 HTTP/1.1" 200 869
Not Found: /blogapp/author/26
"GET /blogapp/author/26 HTTP/1.1" 404 2712
"GET /blogapp/author/2 HTTP/1.1" 200 1500
"GET /blogapp/post/1 HTTP/1.1" 200 1665
Watching for file changes with StatReloader
"GET /blogapp/author/1 HTTP/1.1" 200 1605
"GET /blogapp/author/2 HTTP/1.1" 200 1577
Watching for file changes with StatReloader
"GET /blogapp/author/1 HTTP/1.1" 200 1476
"GET /blogapp/post/116 HTTP/1.1" 200 1582
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /blogapp/post/116 HTTP/1.1" 200 1582
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/models.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /blogapp/post/116 HTTP/1.1" 200 1582
"GET /blogapp/post/146 HTTP/1.1" 200 1602
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /blogapp/post/146 HTTP/1.1" 200 1602
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/models.py changed, reloading.
Watching for file changes with StatReloader
"GET /blogapp/post/146 HTTP/1.1" 200 1602
/home/denis/Documents/GeekBrains/025_Django/django_seminars/blogapp/models.py changed, reloading.
Watching for file changes with StatReloader
"GET /blogapp/post/146 HTTP/1.1" 200 1602
"GET /blogapp/post/146 HTTP/1.1" 200 1602
"GET /blogapp/post/146 HTTP/1.1" 200 1602
"GET /blogapp/post/146 HTTP/1.1" 200 2395
"GET /blogapp/post/146 HTTP/1.1" 200 1812
"GET /blogapp/post/146 HTTP/1.1" 200 1777
"GET /blogapp/post/146 HTTP/1.1" 200 1780
"GET /blogapp/post/146 HTTP/1.1" 200 1778
"GET /blogapp/post/146 HTTP/1.1" 200 2937
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/all_clients HTTP/1.1" 301 0
Internal Server Error: /homework/all_clients/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 37, in all_clients_view
    return render(request, 'all_clients_template.html', context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '()' from 'clients.count()'
"GET /homework/all_clients/ HTTP/1.1" 500 163815
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /homework/all_clients/
"GET /homework/all_clients/ HTTP/1.1" 404 2888
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/all_clients/ HTTP/1.1" 200 2511
"GET /homework/about HTTP/1.1" 200 902
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /homework/all_clients/
"GET /homework/all_clients/ HTTP/1.1" 404 2888
Not Found: /homework/all_clients/
"GET /homework/all_clients/ HTTP/1.1" 404 2888
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /homework/all_clients/ HTTP/1.1" 200 2511
Not Found: /homework/orders_by_client/6
"GET /homework/orders_by_client/6 HTTP/1.1" 404 3127
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Watching for file changes with StatReloader
Not Found: /homework/orders_by_client/6
"GET /homework/orders_by_client/6 HTTP/1.1" 404 3127
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/orders_by_client/6
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: View.__init__() takes 1 positional argument but 2 were given
"GET /homework/orders_by_client/6 HTTP/1.1" 500 64093
Internal Server Error: /homework/orders_by_client/6
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: View.__init__() takes 1 positional argument but 2 were given
"GET /homework/orders_by_client/6 HTTP/1.1" 500 64093
Not Found: /homework/orders_by_client/
"GET /homework/orders_by_client/ HTTP/1.1" 404 3123
Not Found: /homework/orders_by_client/6/
"GET /homework/orders_by_client/6/ HTTP/1.1" 404 3129
Internal Server Error: /homework/orders_by_client/6
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: View.__init__() takes 1 positional argument but 2 were given
"GET /homework/orders_by_client/6 HTTP/1.1" 500 64093
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/orders_by_client/6
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
TypeError: View.__init__() takes 1 positional argument but 2 were given
"GET /homework/orders_by_client/6 HTTP/1.1" 500 64093
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/orders_by_client/6 HTTP/1.1" 200 1
Internal Server Error: /homework/all_clients/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 37, in get
    return render(request, 'all_clients_template.html', context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '(clients)' from 'len(clients)'
"GET /homework/all_clients/ HTTP/1.1" 500 174159
Internal Server Error: /homework/all_clients/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 37, in get
    return render(request, 'all_clients_template.html', context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '()' from 'clients.count()'
"GET /homework/all_clients/ HTTP/1.1" 500 174185
"GET /homework/all_clients/ HTTP/1.1" 200 856
Not Found: /favicon.ico
"GET /homework/all_clients/ HTTP/1.1" 200 861
"GET /homework/all_clients/ HTTP/1.1" 200 861
"GET /homework/all_clients/ HTTP/1.1" 200 2549
"GET /homework/all_clients/ HTTP/1.1" 200 2549
"GET /homework/all_clients/ HTTP/1.1" 200 3803
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/all_clients/ HTTP/1.1" 200 3814
"GET /homework/all_clients/ HTTP/1.1" 200 3935
"GET /homework/all_clients/ HTTP/1.1" 200 3935
"GET /homework/all_clients/ HTTP/1.1" 200 3933
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/all_clients/ HTTP/1.1" 200 3933
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/all_clients/ HTTP/1.1" 200 3933
"GET /homework/all_clients/ HTTP/1.1" 200 4074
"GET /homework/all_clients/ HTTP/1.1" 200 4086
"GET /homework/all_clients/ HTTP/1.1" 200 4273
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/urls.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/all_clients/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 38, in get
    return render(request, 'homeworkapp/all_clients_template.html', context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 315, in render
    return nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 214, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'orders_by_client' not found. 'orders_by_client' is not a valid view function or pattern name.
"GET /homework/all_clients/ HTTP/1.1" 500 224878
"GET /homework/all_clients/ HTTP/1.1" 200 4745
"GET /homework/all_clients/ HTTP/1.1" 200 4745
Internal Server Error: /homework/products_by_client/1/7/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
TypeError: ProductsByClient.get() got an unexpected keyword argument 'days'
"GET /homework/products_by_client/1/7/ HTTP/1.1" 500 73904
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/products_by_client/2/7/ HTTP/1.1" 200 1
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 1
"GET /homework/products_by_client/2/7/ HTTP/1.1" 200 1
"GET /homework/products_by_client/4/7/ HTTP/1.1" 200 1
"GET /homework/products_by_client/5/7/ HTTP/1.1" 200 1
"GET /homework/products_by_client/6/7/ HTTP/1.1" 200 1
"GET /homework/products_by_client/9/7/ HTTP/1.1" 200 1
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/8/7/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 41, in get
    return HttpResponse(str(client_id, days))
TypeError: str() argument 'encoding' must be str, not int
"GET /homework/products_by_client/8/7/ HTTP/1.1" 500 77123
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/products_by_client/8/7/ HTTP/1.1" 200 1
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/products_by_client/8/7/ HTTP/1.1" 200 19
"GET /homework/products_by_client/5/7/ HTTP/1.1" 200 19
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/products_by_client/4/7/ HTTP/1.1" 200 19
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 13
"GET /homework/products_by_client/6/7/ HTTP/1.1" 200 13
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/6/7/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 48, in get
    return HttpResponse(**context)
  File "/usr/lib/python3/dist-packages/django/http/response.py", line 329, in __init__
    super().__init__(*args, **kwargs)
TypeError: HttpResponseBase.__init__() got an unexpected keyword argument 'client'
"GET /homework/products_by_client/6/7/ HTTP/1.1" 500 87786
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/5/7/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_response(request, response)
  File "/usr/lib/python3/dist-packages/django/middleware/clickjacking.py", line 33, in process_response
    response.headers['X-Frame-Options'] = self.get_xframe_options_value(
AttributeError: 'dict' object has no attribute 'headers'
"GET /homework/products_by_client/5/7/ HTTP/1.1" 500 68761
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/4/7/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 48, in get
    return JsonResponse(context)
  File "/usr/lib/python3/dist-packages/django/http/response.py", line 605, in __init__
    data = json.dumps(data, cls=encoder, **json_dumps_params)
  File "/usr/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/usr/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3/dist-packages/django/core/serializers/json.py", line 105, in default
    return super().default(o)
  File "/usr/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Client is not JSON serializable
"GET /homework/products_by_client/4/7/ HTTP/1.1" 500 114801
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/products_by_client/4/7/ HTTP/1.1" 200 3589
"GET /homework/products_by_client/4/7/ HTTP/1.1" 200 3640
"GET /homework/products_by_client/4/7/ HTTP/1.1" 200 3664
"GET /homework/products_by_client/4/7/ HTTP/1.1" 200 3648
"GET /homework/products_by_client/4/7/ HTTP/1.1" 200 3652
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/4/7/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 48, in get
    return render(request, "homeworkapp/all_products_by_client.html", context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 214, in render
    nodelist.append(node.render_annotated(context))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 170, in render
    values = list(values)
TypeError: 'ManyRelatedManager' object is not iterable
"GET /homework/products_by_client/4/7/ HTTP/1.1" 500 194156
Not Found: /favicon.ico
"GET /homework/products_by_client/4/7/ HTTP/1.1" 200 3848
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/4/7/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 43, in get
    ordered = Order.objects.order_by(created).filter(client=client_id, created__lt=datetime.now()-timedelta(days=days)).all()
NameError: name 'created' is not defined
"GET /homework/products_by_client/4/7/ HTTP/1.1" 500 78470
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/products_by_client/4/7/ HTTP/1.1" 200 3848
"GET /homework/products_by_client/4/7/ HTTP/1.1" 200 4197
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/products_by_client/4/7/ HTTP/1.1" 200 4197
"GET /homework/products_by_client/2/7/ HTTP/1.1" 200 4051
"GET /homework/products_by_client/10/7/ HTTP/1.1" 200 4131
"GET /homework/all_clients/ HTTP/1.1" 200 5745
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/products_by_client/2/7/ HTTP/1.1" 200 5087
"GET /homework/products_by_client/2/7/ HTTP/1.1" 200 5279
"GET /homework/all_clients/ HTTP/1.1" 200 5753
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 4726
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 4322
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 6530
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 7056
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 6608
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 7004
Internal Server Error: /homework/products_by_client/1/7/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 49, in get
    return render(request, "homeworkapp/all_products_by_client.html", context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 817, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 817, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '"d-m-y"' from 'order.created|date"d-m-y"'
"GET /homework/products_by_client/1/7/ HTTP/1.1" 500 214024
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 6736
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 6736
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 6752
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 6875
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 6939
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 6875
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 5328
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 5306
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 5306
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 5346
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 5360
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 5359
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 5347
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 5352
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 5377
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 5225
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 5212
"GET /homework/products_by_client/1/7/ HTTP/1.1" 200 5212
"GET /homework/products_by_client/1/10/ HTTP/1.1" 200 5213
"GET /homework/products_by_client/1/365/ HTTP/1.1" 200 2552
"GET /homework/products_by_client/1/365/ HTTP/1.1" 200 2646
"GET /homework/products_by_client/1/365/ HTTP/1.1" 200 2656
Not Found: /favicon.ico
"GET /homework/products_by_client/1/365/ HTTP/1.1" 200 2661
"GET /homework/products_by_client/1/365/ HTTP/1.1" 200 2699
"GET /homework/products_by_client/1/365/ HTTP/1.1" 200 2725
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/products_by_client/1/365/ HTTP/1.1" 200 5387
"GET /homework/products_by_client/10/7/ HTTP/1.1" 200 2721
"GET /homework/products_by_client/7/7/ HTTP/1.1" 200 2729
"GET /homework/products_by_client/7/7/ HTTP/1.1" 200 2729
"GET /homework/products_by_client/3/7/ HTTP/1.1" 200 2721
"GET /homework/all_clients/ HTTP/1.1" 200 5813
"GET /homework/products_by_client/3/365/ HTTP/1.1" 200 4236
Internal Server Error: /homework/products_by_client/3/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 49, in get
    return render(request, "homeworkapp/all_products_by_client.html", context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'product_by_clients' not found. 'product_by_clients' is not a valid view function or pattern name.
"GET /homework/products_by_client/3/365/ HTTP/1.1" 500 181347
Internal Server Error: /homework/products_by_client/3/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 49, in get
    return render(request, "homeworkapp/all_products_by_client.html", context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'product_by_clients' not found. 'product_by_clients' is not a valid view function or pattern name.
"GET /homework/products_by_client/3/365/ HTTP/1.1" 500 181311
Internal Server Error: /homework/products_by_client/3/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 49, in get
    return render(request, "homeworkapp/all_products_by_client.html", context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 170, in render
    return self._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 162, in _render
    return self.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 938, in render
    bit = node.render_annotated(context)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 905, in render_annotated
    return self.render(context)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 449, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/usr/lib/python3/dist-packages/django/urls/base.py", line 86, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/urls/resolvers.py", line 698, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'products_by_clients' not found. 'products_by_clients' is not a valid view function or pattern name.
"GET /homework/products_by_client/3/365/ HTTP/1.1" 500 181330
"GET /homework/products_by_client/3/365/ HTTP/1.1" 200 4378
"GET /homework/products_by_client/3/30/ HTTP/1.1" 200 2864
"GET /homework/products_by_client/3/365/ HTTP/1.1" 200 4378
"GET /homework/products_by_client/3/7/ HTTP/1.1" 200 2863
"GET /homework/products_by_client/9/365/ HTTP/1.1" 200 6995
"GET /homework/products_by_client/9/7/ HTTP/1.1" 200 2859
"GET /homework/products_by_client/9/30/ HTTP/1.1" 200 4528
"GET /homework/products_by_client/9/365/ HTTP/1.1" 200 6995
"GET /homework/products_by_client/9/365/ HTTP/1.1" 200 6895
"GET /homework/products_by_client/2/365/ HTTP/1.1" 200 6348
"GET /homework/products_by_client/3/365/ HTTP/1.1" 200 4367
"GET /homework/all_clients/ HTTP/1.1" 200 5713
"GET /homework/products_by_client/3/365/ HTTP/1.1" 200 4379
"GET /homework/products_by_client/3/365/ HTTP/1.1" 200 4392
"GET /homework/products_by_client/3/365/ HTTP/1.1" 200 4388
"GET /homework/products_by_client/3/365/ HTTP/1.1" 200 4404
"GET /homework/products_by_client/3/365/ HTTP/1.1" 200 4401
"GET /homework/products_by_client/3/365/ HTTP/1.1" 200 4397
"GET /homework/products_by_client/3/365/ HTTP/1.1" 200 4393
"GET /homework/all_clients/ HTTP/1.1" 200 5713
"GET /homework/products_by_client/5/365/ HTTP/1.1" 200 4359
"GET /homework/products_by_client/5/30/ HTTP/1.1" 200 4358
"GET /homework/products_by_client/5/365/ HTTP/1.1" 200 4359
"GET /homework/products_by_client/5/7/ HTTP/1.1" 200 2874
"GET /homework/products_by_client/5/7/ HTTP/1.1" 200 3086
"GET /homework/products_by_client/5/30/ HTTP/1.1" 200 4380
"GET /homework/products_by_client/5/7/ HTTP/1.1" 200 2841
"GET /homework/all_clients/ HTTP/1.1" 200 5713
"GET /homework/products_by_client/9/365/ HTTP/1.1" 200 7032
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/5/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 44, in get
    all_products = (product for product in ordered.products.all())
AttributeError: 'QuerySet' object has no attribute 'products'
"GET /homework/products_by_client/5/365/ HTTP/1.1" 500 79307
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/5/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 44, in get
    all_products = (product.name for product in order for order in ordered.products.all())
NameError: name 'order' is not defined
"GET /homework/products_by_client/5/365/ HTTP/1.1" 500 79213
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/products_by_client/5/365/ HTTP/1.1" 200 4381
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/products_by_client/5/365/ HTTP/1.1" 200 4381
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/products_by_client/5/365/ HTTP/1.1" 200 2843
"GET /homework/products_by_client/5/365/ HTTP/1.1" 200 2843
"GET /homework/products_by_client/5/7/ HTTP/1.1" 200 2841
"GET /homework/products_by_client/5/30/ HTTP/1.1" 200 2842
"GET /homework/products_by_client/6/365/ HTTP/1.1" 200 2847
"GET /homework/products_by_client/6/365/ HTTP/1.1" 200 5285
"GET /homework/products_by_client/6/7/ HTTP/1.1" 200 2845
"GET /homework/products_by_client/6/365/ HTTP/1.1" 200 5285
"GET /homework/products_by_client/6/30/ HTTP/1.1" 200 3992
"GET /homework/products_by_client/6/7/ HTTP/1.1" 200 2845
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/6/7/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 57, in get
    return render(request, "homeworkapp/all_products_by_client.html", context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 967, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 190, in parse
    retval = self.expression()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 200, in expression
    left = t.nud(self)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 144, in nud
    raise parser.error_class("Unexpected end of expression in if tag.")
django.template.exceptions.TemplateSyntaxError: Unexpected end of expression in if tag.
"GET /homework/products_by_client/6/7/ HTTP/1.1" 500 183676
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/6/7/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 57, in get
    return render(request, "homeworkapp/all_products_by_client.html", context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 967, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 190, in parse
    retval = self.expression()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 200, in expression
    left = t.nud(self)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 144, in nud
    raise parser.error_class("Unexpected end of expression in if tag.")
django.template.exceptions.TemplateSyntaxError: Unexpected end of expression in if tag.
"GET /homework/products_by_client/6/7/ HTTP/1.1" 500 183676
Internal Server Error: /homework/products_by_client/6/7/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 57, in get
    return render(request, "homeworkapp/all_products_by_client.html", context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 967, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 190, in parse
    retval = self.expression()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 200, in expression
    left = t.nud(self)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 144, in nud
    raise parser.error_class("Unexpected end of expression in if tag.")
django.template.exceptions.TemplateSyntaxError: Unexpected end of expression in if tag.
"GET /homework/products_by_client/6/7/ HTTP/1.1" 500 183676
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/6/7/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 57, in get
    return render(request, "homeworkapp/all_products_by_client.html", context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 967, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 190, in parse
    retval = self.expression()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 200, in expression
    left = t.nud(self)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 144, in nud
    raise parser.error_class("Unexpected end of expression in if tag.")
django.template.exceptions.TemplateSyntaxError: Unexpected end of expression in if tag.
"GET /homework/products_by_client/6/7/ HTTP/1.1" 500 183676
Internal Server Error: /homework/products_by_client/6/7/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 57, in get
    return render(request, "homeworkapp/all_products_by_client.html", context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 967, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 190, in parse
    retval = self.expression()
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 200, in expression
    left = t.nud(self)
  File "/usr/lib/python3/dist-packages/django/template/smartif.py", line 144, in nud
    raise parser.error_class("Unexpected end of expression in if tag.")
django.template.exceptions.TemplateSyntaxError: Unexpected end of expression in if tag.
"GET /homework/products_by_client/6/7/ HTTP/1.1" 500 183648
"GET /homework/products_by_client/6/7/ HTTP/1.1" 200 2841
Internal Server Error: /homework/products_by_client/6/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 49, in get
    products[product.name] = max(order.created, last_product_date)
TypeError: '>' not supported between instances of 'int' and 'datetime.datetime'
"GET /homework/products_by_client/6/365/ HTTP/1.1" 500 81887
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/6/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 49, in get
    products[product.name] = max(order.created, last_product_date)
TypeError: '>' not supported between instances of 'NoneType' and 'datetime.datetime'
"GET /homework/products_by_client/6/365/ HTTP/1.1" 500 81916
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/6/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 49, in get
    products[product.name] = max(order.created, last_product_date)
TypeError: can't compare offset-naive and offset-aware datetimes
"GET /homework/products_by_client/6/365/ HTTP/1.1" 500 81788
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/6/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 48, in get
    last_product_date = products.setdefault(product.name, datetime.date.min )
AttributeError: 'method_descriptor' object has no attribute 'min'
"GET /homework/products_by_client/6/365/ HTTP/1.1" 500 81619
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/6/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 48, in get
    last_product_date = products.setdefault(product.name, datetime.date(MINYEAR,1,1) )
NameError: name 'MINYEAR' is not defined
"GET /homework/products_by_client/6/365/ HTTP/1.1" 500 81487
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/6/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 48, in get
    last_product_date = products.setdefault(product.name, datetime(MINYEAR,1,1, tzinfo=None) )
NameError: name 'MINYEAR' is not defined
"GET /homework/products_by_client/6/365/ HTTP/1.1" 500 81503
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/6/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 49, in get
    products[product.name] = max(order.created, last_product_date)
TypeError: can't compare offset-naive and offset-aware datetimes
"GET /homework/products_by_client/6/365/ HTTP/1.1" 500 81789
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/6/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 48, in get
    last_product_date = products.setdefault(product.name, datetime(1,1,1, tzInfo=0) )
TypeError: 'tzInfo' is an invalid keyword argument for this function
"GET /homework/products_by_client/6/365/ HTTP/1.1" 500 81597
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/6/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 49, in get
    products[product.name] = max(order.created, last_product_date)
TypeError: can't compare offset-naive and offset-aware datetimes
"GET /homework/products_by_client/6/365/ HTTP/1.1" 500 81792
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/6/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 48, in get
    last_product_date = products.setdefault(product.name, datetime(1,1,1, tzinfo=0) )
TypeError: tzinfo argument must be None or of a tzinfo subclass, not type 'int'
"GET /homework/products_by_client/6/365/ HTTP/1.1" 500 81641
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/6/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 48, in get
    last_product_date = products.setdefault(product.name, datetime.now() - timedelta.max )
OverflowError: date value out of range
"GET /homework/products_by_client/6/365/ HTTP/1.1" 500 81455
Not Found: /favicon.ico
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/6/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 48, in get
    last_product_date = products.setdefault(product.name, datetime.now() - timedelta(year=100) )
TypeError: 'year' is an invalid keyword argument for __new__()
"GET /homework/products_by_client/6/365/ HTTP/1.1" 500 81595
Not Found: /favicon.ico
Internal Server Error: /homework/products_by_client/6/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 48, in get
    last_product_date = products.setdefault(product.name, datetime.now())
TypeError: 'year' is an invalid keyword argument for __new__()
"GET /homework/products_by_client/6/365/ HTTP/1.1" 500 81549
Not Found: /favicon.ico
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/6/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 49, in get
    products[product.name] = max(order.created, last_product_date)
TypeError: can't compare offset-naive and offset-aware datetimes
"GET /homework/products_by_client/6/365/ HTTP/1.1" 500 81824
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/6/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 49, in get
    products[product.name] = max(order.created, last_product_date)
TypeError: '>' not supported between instances of 'type' and 'datetime.datetime'
"GET /homework/products_by_client/6/365/ HTTP/1.1" 500 81982
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/6/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 49, in get
    products[product.name] = max(order.created, last_product_date)
TypeError: can't compare offset-naive and offset-aware datetimes
"GET /homework/products_by_client/6/365/ HTTP/1.1" 500 81824
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/products_by_client/6/365/ HTTP/1.1" 200 5334
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/6/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 49, in get
    last_product_date = products.setdefault(product.name, timezone.activate(datetime.min))
  File "/usr/lib/python3/dist-packages/django/utils/timezone.py", line 99, in activate
    raise ValueError("Invalid timezone: %r" % timezone)
ValueError: Invalid timezone: datetime.datetime(1, 1, 1, 0, 0)
"GET /homework/products_by_client/6/365/ HTTP/1.1" 500 85075
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/6/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 50, in get
    products[product.name] = max(order.created, last_product_date)
TypeError: can't compare offset-naive and offset-aware datetimes
"GET /homework/products_by_client/6/365/ HTTP/1.1" 500 81788
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /homework/products_by_client/6/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 51, in get
    products[product.name] = max(order.created, last_product_date)
TypeError: can't compare offset-naive and offset-aware datetimes
"GET /homework/products_by_client/6/365/ HTTP/1.1" 500 81788
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/products_by_client/6/365/ HTTP/1.1" 200 5334
/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py changed, reloading.
Watching for file changes with StatReloader
"GET /homework/products_by_client/6/365/ HTTP/1.1" 200 4983
"GET /homework/products_by_client/6/365/ HTTP/1.1" 200 2898
"GET /homework/products_by_client/6/365/ HTTP/1.1" 200 2898
Internal Server Error: /homework/products_by_client/6/365/
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/lib/python3/dist-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/denis/Documents/GeekBrains/025_Django/django_seminars/homeworkapp/views.py", line 58, in get
    return render(request, "homeworkapp/all_products_by_client.html", context)
  File "/usr/lib/python3/dist-packages/django/shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib/python3/dist-packages/django/template/loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/backends/django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "/usr/lib/python3/dist-packages/django/template/engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "/usr/lib/python3/dist-packages/django/template/loaders/base.py", line 29, in get_template
    return Template(
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 193, in compile_nodelist
    return parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 278, in do_extends
    nodelist = parser.parse()
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/loader_tags.py", line 216, in do_block
    nodelist = parser.parse(('endblock',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 968, in do_if
    nodelist = parser.parse(('elif', 'else', 'endif'))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 478, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "/usr/lib/python3/dist-packages/django/template/defaulttags.py", line 817, in do_for
    nodelist_loop = parser.parse(('empty', 'endfor',))
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 449, in parse
    raise self.error(token, e)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 447, in parse
    filter_expression = self.compile_filter(token.contents)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 563, in compile_filter
    return FilterExpression(token, self)
  File "/usr/lib/python3/dist-packages/django/template/base.py", line 662, in __init__
    raise TemplateSyntaxError("Could not parse the remainder: '%s' "
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: '[product]' from 'products[product]'
"GET /homework/products_by_client/6/365/ HTTP/1.1" 500 216896
"GET /homework/products_by_client/6/30/ HTTP/1.1" 200 4041
Not Found: /favicon.ico
"GET /homework/products_by_client/6/30/ HTTP/1.1" 200 4321
"GET /homework/products_by_client/6/365/ HTTP/1.1" 200 5934
